name: fluestr
description: A mobile client for the Nostr protocol

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bip340:
    git: https://github.com/fiatjaf/dart-bip340
  bitcoin_flutter:
    git: https://github.com/fusion44/bitcoin_flutter
  web_socket_channel: ^2.1.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  crypto: ^3.0.1
  buffer: ^1.0.7
  flutter_spinkit: ^5.1.0
  timeago: ^3.1.0
  flutter_i18n: ^0.31.1
  pin_code_fields: ^7.3.0
  flutter_overboard: ^3.1.1
  flutter_translate: ^3.0.1
  go_router: ^3.0.1
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  hex: ^0.2.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.7


flutter:
  uses-material-design: true
  
  assets:
    # i18n
    - assets/i18n/
